// deposits.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: deposits.proto

package deposit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddDepositRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletGuid      string `protobuf:"bytes,1,opt,name=wallet_guid,json=walletGuid,proto3" json:"wallet_guid,omitempty"`
	UserGuid        string `protobuf:"bytes,2,opt,name=user_guid,json=userGuid,proto3" json:"user_guid,omitempty"`
	AssetGuid       string `protobuf:"bytes,3,opt,name=asset_guid,json=assetGuid,proto3" json:"asset_guid,omitempty"`
	TransactionGuid string `protobuf:"bytes,4,opt,name=transaction_guid,json=transactionGuid,proto3" json:"transaction_guid,omitempty"`
	FromAddress     string `protobuf:"bytes,5,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress       string `protobuf:"bytes,6,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount          string `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	TxHash          string `protobuf:"bytes,8,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TxFee           string `protobuf:"bytes,9,opt,name=tx_fee,json=txFee,proto3" json:"tx_fee,omitempty"`
	Status          int32  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AddDepositRequest) Reset() {
	*x = AddDepositRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposits_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDepositRequest) ProtoMessage() {}

func (x *AddDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deposits_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDepositRequest.ProtoReflect.Descriptor instead.
func (*AddDepositRequest) Descriptor() ([]byte, []int) {
	return file_deposits_proto_rawDescGZIP(), []int{0}
}

func (x *AddDepositRequest) GetWalletGuid() string {
	if x != nil {
		return x.WalletGuid
	}
	return ""
}

func (x *AddDepositRequest) GetUserGuid() string {
	if x != nil {
		return x.UserGuid
	}
	return ""
}

func (x *AddDepositRequest) GetAssetGuid() string {
	if x != nil {
		return x.AssetGuid
	}
	return ""
}

func (x *AddDepositRequest) GetTransactionGuid() string {
	if x != nil {
		return x.TransactionGuid
	}
	return ""
}

func (x *AddDepositRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *AddDepositRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *AddDepositRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *AddDepositRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *AddDepositRequest) GetTxFee() string {
	if x != nil {
		return x.TxFee
	}
	return ""
}

func (x *AddDepositRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AddDepositResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid string `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
}

func (x *AddDepositResponse) Reset() {
	*x = AddDepositResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposits_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDepositResponse) ProtoMessage() {}

func (x *AddDepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deposits_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDepositResponse.ProtoReflect.Descriptor instead.
func (*AddDepositResponse) Descriptor() ([]byte, []int) {
	return file_deposits_proto_rawDescGZIP(), []int{1}
}

func (x *AddDepositResponse) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

var File_deposits_proto protoreflect.FileDescriptor

var file_deposits_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x22, 0xbd, 0x02, 0x0a, 0x11, 0x41, 0x64,
	0x64, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x47, 0x75, 0x69, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x47, 0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x47, 0x75, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x10,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x75, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x47, 0x75, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66,
	0x72, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x78,
	0x5f, 0x66, 0x65, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x78, 0x46, 0x65,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x28, 0x0a, 0x12, 0x41, 0x64, 0x64,
	0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67,
	0x75, 0x69, 0x64, 0x32, 0x57, 0x0a, 0x0e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x12, 0x1a, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x41, 0x64,
	0x64, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2e, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_deposits_proto_rawDescOnce sync.Once
	file_deposits_proto_rawDescData = file_deposits_proto_rawDesc
)

func file_deposits_proto_rawDescGZIP() []byte {
	file_deposits_proto_rawDescOnce.Do(func() {
		file_deposits_proto_rawDescData = protoimpl.X.CompressGZIP(file_deposits_proto_rawDescData)
	})
	return file_deposits_proto_rawDescData
}

var file_deposits_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_deposits_proto_goTypes = []interface{}{
	(*AddDepositRequest)(nil),  // 0: deposit.AddDepositRequest
	(*AddDepositResponse)(nil), // 1: deposit.AddDepositResponse
}
var file_deposits_proto_depIdxs = []int32{
	0, // 0: deposit.DepositService.AddDeposit:input_type -> deposit.AddDepositRequest
	1, // 1: deposit.DepositService.AddDeposit:output_type -> deposit.AddDepositResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_deposits_proto_init() }
func file_deposits_proto_init() {
	if File_deposits_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_deposits_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDepositRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposits_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDepositResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_deposits_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deposits_proto_goTypes,
		DependencyIndexes: file_deposits_proto_depIdxs,
		MessageInfos:      file_deposits_proto_msgTypes,
	}.Build()
	File_deposits_proto = out.File
	file_deposits_proto_rawDesc = nil
	file_deposits_proto_goTypes = nil
	file_deposits_proto_depIdxs = nil
}
